baseURL = "/"
title = "Robert Lankford"
theme = "beautifulhugo"
languageCode = "en-us"
metaDataFormat = "yaml"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Params]
  mainSections = ["blog"]
  dateFormat = "January 2, 2006"

  highlightjsVersion = "9.11.0"
  highlightjsLang = ["r", "yaml"]

[Author]
  name = "Robert Lankford"

[[menu.main]]
  name = "Blog"
  url = "blog/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  weight = 2

[[menu.main]]
  parent = "about"
  name = "About Me"
  url = "about/"
  weight = 1

[[menu.main]]
  parent = "about"
  name = "Resume"
  url = "about/resume"
  weight = 2

[[menu.main]]
  name = "Demos"
  url = "demo/"
  weight = 3
